/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: procnet.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "procnet.pb-c.h"
void   hello__init
                     (Hello         *message)
{
  static const Hello init_value = HELLO__INIT;
  *message = init_value;
}
size_t hello__get_packed_size
                     (const Hello *message)
{
  assert(message->base.descriptor == &hello__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hello__pack
                     (const Hello *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hello__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hello__pack_to_buffer
                     (const Hello *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hello__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hello *
       hello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hello *)
     protobuf_c_message_unpack (&hello__descriptor,
                                allocator, len, data);
}
void   hello__free_unpacked
                     (Hello *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hello__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   config__init
                     (Config         *message)
{
  static const Config init_value = CONFIG__INIT;
  *message = init_value;
}
size_t config__get_packed_size
                     (const Config *message)
{
  assert(message->base.descriptor == &config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t config__pack
                     (const Config *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t config__pack_to_buffer
                     (const Config *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Config *
       config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Config *)
     protobuf_c_message_unpack (&config__descriptor,
                                allocator, len, data);
}
void   config__free_unpacked
                     (Config *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   buf__init
                     (Buf         *message)
{
  static const Buf init_value = BUF__INIT;
  *message = init_value;
}
size_t buf__get_packed_size
                     (const Buf *message)
{
  assert(message->base.descriptor == &buf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t buf__pack
                     (const Buf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &buf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t buf__pack_to_buffer
                     (const Buf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &buf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Buf *
       buf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Buf *)
     protobuf_c_message_unpack (&buf__descriptor,
                                allocator, len, data);
}
void   buf__free_unpacked
                     (Buf *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &buf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue hello__system_type__enum_values_by_number[3] =
{
  { "CONTROLLER", "HELLO__SYSTEM_TYPE__CONTROLLER", 1 },
  { "FORWARDER", "HELLO__SYSTEM_TYPE__FORWARDER", 2 },
  { "NODE", "HELLO__SYSTEM_TYPE__NODE", 3 },
};
static const ProtobufCIntRange hello__system_type__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex hello__system_type__enum_values_by_name[3] =
{
  { "CONTROLLER", 0 },
  { "FORWARDER", 1 },
  { "NODE", 2 },
};
const ProtobufCEnumDescriptor hello__system_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Hello.SystemType",
  "SystemType",
  "Hello__SystemType",
  "",
  3,
  hello__system_type__enum_values_by_number,
  3,
  hello__system_type__enum_values_by_name,
  1,
  hello__system_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor hello__field_descriptors[5] =
{
  {
    "system_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Hello, system_type),
    &hello__system_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auth_token",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Hello, auth_token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Hello, system_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_version",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Hello, system_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_count",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Hello, has_node_count),
    offsetof(Hello, node_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hello__field_indices_by_name[] = {
  1,   /* field[1] = auth_token */
  4,   /* field[4] = node_count */
  2,   /* field[2] = system_name */
  0,   /* field[0] = system_type */
  3,   /* field[3] = system_version */
};
static const ProtobufCIntRange hello__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor hello__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Hello",
  "Hello",
  "Hello",
  "",
  sizeof(Hello),
  5,
  hello__field_descriptors,
  hello__field_indices_by_name,
  1,  hello__number_ranges,
  (ProtobufCMessageInit) hello__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue config__synchronization__enum_values_by_number[3] =
{
  { "DETERMINISTIC", "CONFIG__SYNCHRONIZATION__DETERMINISTIC", 1 },
  { "SEMIDETERMINISTIC", "CONFIG__SYNCHRONIZATION__SEMIDETERMINISTIC", 2 },
  { "NONDETERMINISTIC", "CONFIG__SYNCHRONIZATION__NONDETERMINISTIC", 3 },
};
static const ProtobufCIntRange config__synchronization__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex config__synchronization__enum_values_by_name[3] =
{
  { "DETERMINISTIC", 0 },
  { "NONDETERMINISTIC", 2 },
  { "SEMIDETERMINISTIC", 1 },
};
const ProtobufCEnumDescriptor config__synchronization__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Config.Synchronization",
  "Synchronization",
  "Config__Synchronization",
  "",
  3,
  config__synchronization__enum_values_by_number,
  3,
  config__synchronization__enum_values_by_name,
  1,
  config__synchronization__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor config__field_descriptors[5] =
{
  {
    "node_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Config, node_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sync",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Config, sync),
    &config__synchronization__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_granularity",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Config, time_granularity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tick_time",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Config, has_tick_time),
    offsetof(Config, tick_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_prefix",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Config, has_ipv6_prefix),
    offsetof(Config, ipv6_prefix),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned config__field_indices_by_name[] = {
  4,   /* field[4] = ipv6_prefix */
  0,   /* field[0] = node_id */
  1,   /* field[1] = sync */
  3,   /* field[3] = tick_time */
  2,   /* field[2] = time_granularity */
};
static const ProtobufCIntRange config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Config",
  "Config",
  "Config",
  "",
  sizeof(Config),
  5,
  config__field_descriptors,
  config__field_indices_by_name,
  1,  config__number_ranges,
  (ProtobufCMessageInit) config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue buf__buf_type__enum_values_by_number[5] =
{
  { "BUF_PACKET", "BUF__BUF_TYPE__BUF_PACKET", 1 },
  { "BUF_ACK", "BUF__BUF_TYPE__BUF_ACK", 2 },
  { "BUF_STDIN", "BUF__BUF_TYPE__BUF_STDIN", 3 },
  { "BUF_STDOUT", "BUF__BUF_TYPE__BUF_STDOUT", 4 },
  { "BUF_STDERR", "BUF__BUF_TYPE__BUF_STDERR", 5 },
};
static const ProtobufCIntRange buf__buf_type__value_ranges[] = {
{1, 0},{0, 5}
};
static const ProtobufCEnumValueIndex buf__buf_type__enum_values_by_name[5] =
{
  { "BUF_ACK", 1 },
  { "BUF_PACKET", 0 },
  { "BUF_STDERR", 4 },
  { "BUF_STDIN", 2 },
  { "BUF_STDOUT", 3 },
};
const ProtobufCEnumDescriptor buf__buf_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Buf.BufType",
  "BufType",
  "Buf__BufType",
  "",
  5,
  buf__buf_type__enum_values_by_number,
  5,
  buf__buf_type__enum_values_by_name,
  1,
  buf__buf_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor buf__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Buf, type),
    &buf__buf_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Buf, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jiffies",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Buf, has_jiffies),
    offsetof(Buf, jiffies),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Buf, has_packet_id),
    offsetof(Buf, packet_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Buf, has_rssi),
    offsetof(Buf, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Buf, has_channel),
    offsetof(Buf, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned buf__field_indices_by_name[] = {
  5,   /* field[5] = channel */
  1,   /* field[1] = data */
  2,   /* field[2] = jiffies */
  3,   /* field[3] = packet_id */
  4,   /* field[4] = rssi */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange buf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor buf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Buf",
  "Buf",
  "Buf",
  "",
  sizeof(Buf),
  6,
  buf__field_descriptors,
  buf__field_indices_by_name,
  1,  buf__number_ranges,
  (ProtobufCMessageInit) buf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
